-- 人员继教管理 - 生免室人员档案导入
-- 生成时间: auto
USE lab_management; -- 请按实际库名调整

INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('吕文娟', '女', '1985.12.5', '大学本科', '主管检验师', '无', '群众', '继续教育与人员培训', '2008.7', '2007.6', '2009.8', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('夏立娇', '女', '1984.10.10', '大学本科', '主管检验师', '无', '群众', '试剂订购', '2010.8', '2009.6', '2010.11', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('姚建民', '女', '1975年11月', '本科', '主管检验师', '组员', '中共党员', '完成生免组日常工作', '1995年7月', '1995年7月', '2008年7月', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('孔亚龙', '男', '1989.9', '研究生', '主管技师', '无', '党员', '凝血检验', '2015.2', '2015.2', '2021.9', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('张婵媛', '女', '1987.2', '博士', '主治医师', '科室秘书', '中共党员', '无', '2015.7', '2015.7', '2019.4', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('朱春阳', '男', '1987.09.01', '大学本科', '主管检验师', '无', '群众', '质控员', '2012.8', '2011.6', '2012.8', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('杨静', '女', '1972.12', '大专', '主管技师', '无', '群众', '生化组长', '1991.7', '1991.7', '1996', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('王春馨', '女', '1973年3月', '本科', '主管检验师', '组员', '中共党员', '完成生免组日常工作', '1991年7月', '1991年7月', '1991年7月', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('王淑华', '女', '1981.9', '硕士研究生', '副主任医师', '无', '群众', '发放微生物检验报告、负责血培养仪保', '2007.7', '2007.7', '2023.7', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('秦东芳', '女', '1984.12.7', '大学本科', '主管检验师', '无', '中共党员', '免疫试剂订购', '2009.7', '2014.8', '2018.8', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('秦满红', '女', '1974.10', '大专', '主管技师', '无', '群众', '', '1997.07', '2003.11', '2007', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('赵海元', '男', '1986.12.16', '大学本科', '主管检验师', '无', '群众', 'LIS系统维护', '2011.7', '2010.6', '2011.7', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('赵瑞', '女', '1994.02', '博士', '医师', '无', '群众', '无', '2024.8', '2024.8', '2025.04', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('郑飞', '女', '1987.6', '本科', '中级', '检验师', '群众', '无', '2006.10', '2006.10', '2016.10', 'admin', '从 BG-KS-GL-017 档案导入');
INSERT INTO personnel_master (name, gender, birth_date, education, title, position, political_status, group_duty, work_start, hospital_join, group_join, created_by, remark) VALUES ('金子铮', '男', '1994.10', '硕士', '主治医师', '无', '中共党员', '免疫组组长', '2020.8', '2020.8', '2021.9', 'admin', '从 BG-KS-GL-017 档案导入');